Copied from jekyll

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,26 +12,26 @@ jobs:
         steps:
             - name: Checkout
               uses: actions/checkout@v4
-
             - name: Setup Ruby
-              uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 #v1.254.0
+              # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
+              uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
               with:
                 ruby-version: '3.4' # Not needed with a .ruby-version file
                 bundler-cache: true # runs 'bundle install' and caches installed gems automatically
-                cache-version: 0
-            # - name: Setup Pages
-            #   id: pages
-            #   uses: actions/configure-pages@v5
-            - name: Check Deployment
-              run: bundle exec jekyll build
+                cache-version: 0 # Increment this number if you need to re-download cached gems
+            - name: Setup Pages
+              id: pages
+              uses: actions/configure-pages@v5
+            - name: Build with Jekyll
+              # Outputs to the './_site' directory by default
+              run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
               env:
-               GITHUB_PAGES: false
-               JEKYLL_ENV: production
+                JEKYLL_ENV: production
             - name: Verify Deployment
               run: |
-                if [ ! -d "_site" ]; then
-                    echo "Deployment failed: _site directory not found."
-                    exit 1
-                fi
-                echo "Deployment check passed: _site directory exists."
+                 if [ ! -d "_site" ]; then
+                  echo "Deployment failed: _site directory not found."
+                  exit 1
+                 fi
+                  echo "Deployment check passed: _site directory exists."
               
